---
local_service_file_path: /home/ubuntu/radhey/release/config/cron/
remote_service_file_path: /etc/systemd/system/
local_config_file_path: /home/ubuntu/radhey/release/config/cron/conf/
remote_config_file_path: /etc/assessment/
remote_cron_folder: /opt/assessment_cron/
geoip_local_file_path: /home/ubuntu/radhey/GeoIP/GeoIP2-Country.mmdb
geoip_remote_file_path: /usr/share/GeoIP/GeoIP2-Country.mmdb