---
  - name: Disable Traffic on Selected Machine
    uri:
      url: "http://{{ inventory_hostname }}:9090/configure?traffic=off"
      follow_redirects: none
      method: GET
    register: _result
    delegate_to: 127.0.0.1
    ignore_errors: yes
  - name: Pausing for 35 seconds for connections to drain
    pause: seconds=35
  - name: Stopping Api service apiservice
    service: name=apiservice state=stopped