---
- name: Copy default.conf file
  copy:
    src: default.conf
    dest: "{{ remote_config_file_path }}"
    mode: 0644
    owner: ubuntu
    group: ubuntu
  become: yes
- name: Synchronization candidate content to remote
  synchronize:
    src: "{{ local_interview_cand_release }}"
    dest: "{{ remote_interview_cand_release }}"
    checksum: yes
    times: no
  become: yes
- name: Creating Nginx Image For Interview Candidate container
  docker_container:
    name: nginxinterviewcand
    image: nginx
    recreate: yes
    pull: yes
    restart_policy: always
    detach: yes
    log_driver: json-file
    log_opt:
      max-size: '{{ log_opt_max_size }}'
      max-file: '{{ log_opt_max_file }}'
    volumes:
    - "{{remote_interview_cand_release}}:/usr/share/nginx/html"
    - "{{remote_config_file_path}}:/etc/nginx/conf.d"
    ports:
    - "4600:80"
    #memory: '{{ docker_memory_limit }}'