---
- hosts: code1,code2
  gather_facts: false
  become: yes
  serial: "10%"
  max_fail_percentage: 100
  roles:
  - coding-server-setup
  tags:
  - setup

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - secret.yaml
  roles:
  - create_backend_build
  tags:
  - build

- hosts: code1,code2
  gather_facts: false
  become: yes
  serial: "10%"
  max_fail_percentage: 100
  roles:
  - deploy_backend
  tags:
  - deploy
