---
  - name: Check for repo folder exist
    stat:
      path: '{{repo_base_path}}/{{repo_name}}'
    register: p
  - name: Resetting local changes
    shell:
      cmd: "git reset --hard"
      chdir: '{{repo_base_path}}/{{repo_name}}'
    when: p.stat.exists
    delegate_to: localhost
  - name: Pulling code from master branch
    git:
      repo: 'https://{{ GIT_USER_NAME | urlencode }}:{{ GIT_PASSWORD | urlencode }}@bitbucket.org/times_internet/{{ repo_name }}.git'
      dest: '{{repo_base_path}}/{{repo_name}}'
      version: master
    when: p.stat.exists
    delegate_to: localhost
  - name: Ansible Git Module with Username Password.
    git:
     repo: 'https://{{ GIT_USER_NAME | urlencode }}:{{ GIT_PASSWORD | urlencode }}@bitbucket.org/times_internet/{{ repo_name }}.git'
     dest: '{{repo_base_path}}/{{repo_name}}'
    when: not p.stat.exists
    delegate_to: localhost
  - name: Copy environment file to build directory.
    copy:
      src: environment.prod.ts
      dest: '{{build_repo_environment_file}}'
    delegate_to: localhost
  - name: Running build command npm i --save && ng build --prod
    shell:
      cmd: "npm i --save && ng build --prod"
      chdir: '{{repo_base_path}}/{{repo_name}}'
    register: ng_result
  - name: "ng build task output"
    debug:
     var: ng_result
  - name: Clean artifact path
    file:
      state: absent
      path: '{{release_base_folder}}/interview_cms/'
    delegate_to: localhost
  - name: copy build file locally.
    copy:
      src: '{{repo_base_path}}/{{repo_name}}/dist/assessment-interview/'
      dest: '{{release_base_folder}}/interview_cms/'
    delegate_to: localhost