---
  - name: "Calling Url for creating fleet autoscaler on k8s server"
    uri:
      url: http://prod-assessment-backend-654996291.ap-south-1.elb.amazonaws.com/admin/createautoscalefleet
      method: POST
      body: "{{ item }}"
      status_code: 200
      body_format: json
    loop: "{{ create_fleet_autoscaler_request }}"
    when: "item.fleetAutoScalerName == 'monovncbased-autoscaler'"
    register: result
  - name: Url Response
    debug:
      msg: "{{result.results}}"