---
- name: Log into aws ecr docker registry
  shell: "$(/usr/local/bin/aws ecr get-login --no-include-email --region ap-south-1)"
- name: Creating NginxProxyApp container
  docker_container:
    name: nginxProxyApp
    image: 845770902133.dkr.ecr.ap-south-1.amazonaws.com/tg-nginx-proxy:1.1
    recreate: yes
    pull: yes
    restart_policy: always
    detach: yes
    log_driver: json-file
    log_opt:
      max-size: '{{ log_opt_max_size }}'
      max-file: '{{ log_opt_max_file }}'
    ports:
    - "8181:80"
    #memory: '{{ docker_memory_limit }}'