log_opt_max_size: "50M"
log_opt_max_file: "5"
docker_memory_limit: "1024M"
remote_config_file_path: /opt/nginx_candidate_config/
local_cand_release: /home/ubuntu/radhey/release/candidate/
remote_cand_release: /opt/nginx_cand/