---
- name: Copy cms content to remote
  copy:
    src: '{{ local_cms_release }}'
    dest: '{{ remote_cms_release }}'

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  become: yes