---
- name: Cleaning old log of containers
  shell:
    cmd: 'sh -c "truncate -s 0 /var/lib/docker/containers/*/*-json.log"'
  become: yes
- name: Stopping candidate container
  docker_container:
    name: nginxcand
    state: stopped